apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quest-node-app-rearc-secret
  namespace: quest-node-apps
spec:
  refreshInterval: 0s
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.global.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: super-secret
    remoteRef:
      key: {{ .Values.global.secret.name }}
      version: AWSCURRENT